import './global.css';

// some change2
export const metadata = {
  title: 'Welcome to mynext',
  description: 'Generated by create-nx-workspace',
};
x =  jfjf--=sf

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
